INSERT INTO RATING(NAME) VALUES('Perfect');
INSERT INTO RATING(NAME) VALUES('Excellent');
INSERT INTO RATING(NAME) VALUES('Good enough');
INSERT INTO RATING(NAME) VALUES('Awful');

INSERT INTO GENRE(NAME) VALUES('Sci-Fi');
INSERT INTO GENRE(NAME) VALUES('Action');
INSERT INTO GENRE(NAME) VALUES('Adventure');

INSERT INTO LANGUAGE(NAME) VALUES('English');
INSERT INTO LANGUAGE(NAME) VALUES('Spanish');
INSERT INTO LANGUAGE(NAME) VALUES('German');

INSERT INTO AUDIO(NAME) VALUES('Sci-Fi');
INSERT INTO AUDIO(NAME) VALUES('Adventure');

INSERT INTO MOVIE(TITLE, LENGTH, REALEASEDATE, IMDB, RATING) VALUES('The Avengers', 143, DATE '2012-05-01', 'tt0848228', 1);
INSERT INTO MOVIE(TITLE, LENGTH, REALEASEDATE, IMDB, RATING) VALUES('Sherlock Holmes', 128, DATE '2010-01-01', 'tt0988045', 2);

INSERT INTO MOVIE_GENRE(MOVIE_ID, GENRE_ID) VALUES(1, 1);
INSERT INTO MOVIE_GENRE(MOVIE_ID, GENRE_ID) VALUES(1, 3);
INSERT INTO MOVIE_GENRE(MOVIE_ID, GENRE_ID) VALUES(2, 2);

INSERT INTO DVD(MOVIE_ID, ISBN, EDITION, SCREEN_FORMAT, REGION) VALUES(1, 'isbn1', 'Standard', '16:9', 'BG');
INSERT INTO DVD(MOVIE_ID, ISBN, EDITION, SCREEN_FORMAT, REGION) VALUES(2, 'isbn2', 'Standard', '16:9', 'UK');

INSERT INTO DVD_AUDIO(DVD_ID, AUDIO_ID) VALUES(1, 1);
INSERT INTO DVD_AUDIO(DVD_ID, AUDIO_ID) VALUES(1, 2);
INSERT INTO DVD_AUDIO(DVD_ID, AUDIO_ID) VALUES(2, 2);

INSERT INTO DVD_LANGUAGE(DVD_ID, LANGUAGE_ID) VALUES(1, 1);
INSERT INTO DVD_LANGUAGE(DVD_ID, LANGUAGE_ID) VALUES(1, 1);
INSERT INTO DVD_LANGUAGE(DVD_ID, LANGUAGE_ID) VALUES(2, 2);