INSERT INTO RATING(NAME) VALUES('Perfect');
INSERT INTO RATING(NAME) VALUES('Excellent');
INSERT INTO RATING(NAME) VALUES('Good enough');
INSERT INTO RATING(NAME) VALUES('Awful');

INSERT INTO GENRE(NAME) VALUES('Sci-Fi');
INSERT INTO GENRE(NAME) VALUES('Adventure');

INSERT INTO LANGUAGE(NAME) VALUES('English');
INSERT INTO LANGUAGE(NAME) VALUES('Spanish');
INSERT INTO LANGUAGE(NAME) VALUES('German');

INSERT INTO AUDIO(NAME) VALUES('Sci-Fi');
INSERT INTO AUDIO(NAME) VALUES('Adventure');

INSERT INTO MOVIE(NAME) VALUES('Sci-Fi');
INSERT INTO MOVIE(NAME) VALUES('Adventure');

INSERT INTO AUDIO(NAME) VALUES('Sci-Fi');
INSERT INTO AUDIO(NAME) VALUES('Adventure');